### ISSUE TITLE
Error in spatial feature map resolution in neck?

### ISSUE THREAD

**Issue by Byte247** [StiphyJay/FastPillars#10]
In the paper the neck is combining stage 3 output and a stage 4 feature maps. Based on section 3.3 these feature maps should be 16x and 8x reduced spatial shapes. But the ResNet with [6,6,3,1] configuration outputs 16x and 32x reduced spatial feature maps at these stages. Is that a mistake in the paper or am I interpreting Figure 1 wrong?

What is your final downsampeling factor before passing the features to the center-head?

**Comment by StiphyJay** [comment]
1. Final downsampeling factor is 1/8, which is consistent with PillarNet and CenterPoint. 2. We remove the downsampeling operation in the first stage.

**Comment by Byte247** [comment]
ah okay thanks for the reply!
