### ISSUE TITLE
nuScenes validation results

### ISSUE THREAD

**Issue by Byte247** [StiphyJay/FastPillars#11]
Hi and sorry to bother you again,

I could not find any results on the nuScenes validation split in the paper. Do you have results here and would you be willing to share them?

**Comment by StiphyJay** [comment]
Hi，sorry for late response.  The results on the nuScenes validation split is 68.2 NDS and 61.3 mAP.

**Comment by Byte247** [comment]
Thanks for your answer. Wow that are very high results. Even higher than fusion based systems like TransFusion that has only 65.55 NDS with a pillar based backbone. 
Do you have an explanation for that?

**Comment by StiphyJay** [comment]
> Thanks for your answer. Wow that are very high results. Even higher than fusion based systems like TransFusion that has only 65.55 NDS with a pillar based backbone.

I think this is attributed to the design of our MAPE module and powerful backbone network. Firstly, the utilization of the MAPE module allows for the preservation of a greater amount of information within each pillar during PFE. Secondly, a powerful backbone network specifically designed for point cloud modalities enhances the pillar representation, meanwhile maintaining the ability of deployment-friendly.
