### ISSUE TITLE
How train the model for the detection of Waymo test dataset?

### ISSUE THREAD

**Issue by qifeng22** [StiphyJay/FastPillars#15]
Hello, thanks you excellent work. I want to how train the model for the detection of Waymo test dataset. In the pillarnet, I train the model in the train dataset, use trained model to detect waymo test dataset, but the result not perfect.
![image](https://github.com/user-attachments/assets/5383dbe6-1a76-43af-ba20-417b1e220af1)

**Comment by qifeng22** [comment]
@StiphyJay

**Comment by StiphyJay** [comment]
> Hello, thanks you excellent work. I want to how train the model for the detection of Waymo test dataset. In the pillarnet, I train the model in the train dataset, use trained model to detect waymo test dataset, but the result not perfect. ![image](https://private-user-images.githubusercontent.com/57132534/358801949-5383dbe6-1a76-43af-ba20-417b1e220af1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4OTQ4MTksIm5iZiI6MTcyMzg5NDUxOSwicGF0aCI6Ii81NzEzMjUzNC8zNTg4MDE5NDktNTM4M2RiZTYtMWE3Ni00M2FmLWJhMjAtNDE3YjFlMjIwYWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDExMzUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZmEyYmNkZmNjYmVlZTE1OTE0ZjZkZDM4MTdhMGYyNmUzMDc1MzU2YTZkNjFkN2E3NmU1Y2FiYmQ5MjlhZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EBUHB19t5eyPEyT3MWBjLV1QqGxZh8yPbaFKVsYbfrA)

Add the val set to train, could improve the performance in test set.
