### ISSUE TITLE
The detail of MAPE

### ISSUE THREAD

**Issue by ouyangziyao** [StiphyJay/FastPillars#16]
Thank you for your excellent work. How does MAPE implement the attention in each pillar? [https://github.com/StiphyJay/FastPillars/issues/6](url) In this issue, this code demonstrates that the point cloud is processed by setting a fixed number of voxels and a fixed number of points per voxel. However, in your paper, it seems to describe a dynamic encoding approach that does not require predefining the number of pillars or the number of points within each pillar. If each pillar contains a different number of points, how is attention applied to aggregate the point features effectively?

**Comment by StiphyJay** [comment]
Code has been released. Please refer the code for more details. Thanks!

**Comment by ouyangziyao** [comment]
Thank you!

**Comment by ouyangziyao** [comment]
Thank you!

**Comment by pedestrain123** [comment]
@StiphyJay @ouyangziyao 您好，请问MAPE部分代码在什么地方？可以告知一下吗？我没有找到
