### ISSUE TITLE
some details about the MAPE

### ISSUE THREAD

**Issue by wcshen** [StiphyJay/FastPillars#2]
1. How to calculate the minimums of point cloud?
2. If the number of points in each pillar is different, then how the ` MLP ` deal with the dynamic size input?

![image](https://user-images.githubusercontent.com/38600406/221548872-627b2eec-b2bf-4dbb-9190-5cae943473d5.png)

**Comment by StiphyJay** [comment]
Thanks for your attention! 

Q1.  the minimums of point cloud which means point cloud range minimum value, such as pc_range=[-54, -54, -5.0, 54, 54, 3.0] in config file, so the x/y/z minimum value is -54/-54/-5. In other words, we convert absolute point coordinate to relative coordinate. It is a common operation in BEV-based lidar detection. We will clarify it more clearly.

Q2. the dimension of the point feature is fixed, we only need to use a MLP to map every point's feature to another fixed dimension without considering the number of points. For MLP, it only needs to fix the input and output dimension.

**Comment by wcshen** [comment]
> Thanks for your attention!
> 
> Q1. the minimums of point cloud which means point cloud range minimum value, such as pc_range=[-54, -54, -5.0, 54, 54, 3.0] in config file, so the x/y/z minimum value is -54/-54/-5. In other words, we convert absolute point coordinate to relative coordinate. It is a common operation in BEV-based lidar detection. We will clarify it more clearly.
> 
> Q2. the dimension of the point feature is fixed, we only need to use a MLP to map every point's feature to another fixed dimension without considering the number of points. For MLP, it only needs to fix the input and output dimension.

tks for relpay!
About Q2, does the MLP in every pillar share weight?

**Comment by wcshen** [comment]
Thanks for your replay!

**Comment by wcshen** [comment]
One more question in MAPE:
1. What's the meaning of symbol `j`
2. Is this attention operation robust to rotations or shuffle of the points as good as max-pooling.
![image](https://user-images.githubusercontent.com/38600406/222123343-6697804b-2f57-4b2d-a1e0-af5b8c0c280f.png)

**Comment by StiphyJay** [comment]
Q1:  j means the point index in the same pillar. For example, one pillar has 5 points, j=0,1,2,3,4. The summation operation will perform on the dimension of points number in one pillar. refer to Fig2. we will modify this equation.
Q2: I think it is robust for rotations or shuffle operations. In the training process, we adopt random global rotation or shuffle operation on the whole point cloud, and the MAPE module can bring performance improvement with 4 ms latency.
