### ISSUE TITLE
About some details

### ISSUE THREAD

**Issue by wcshen** [StiphyJay/FastPillars#3]
Hello, i'm coming again to ask some details:
![image](https://user-images.githubusercontent.com/38600406/233834551-1329a193-6dd4-4a4e-927f-93f9a3b0b4f8.png)

![image](https://user-images.githubusercontent.com/38600406/233834654-d933312f-0f56-4931-b306-85e530dd712e.png)

In the version i read, i didn't find the details about the yellow highlights in the experiments, can you share this part?

**Comment by StiphyJay** [comment]
Thanks for your attention. We didn't put the detailed experimental results of this part in arxiv version. In this part, we find that the number of neck convolution will  affect the final network performance. When the number of neck convolution layers is reduced from 5 to 1, the final performance will decrease about 1.1 map.
